version: '3.9'
services:
    portainer-ce:
        ports:
            - '5086:9000'
            - '9443:9443'
        container_name: portainer
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'portainer_data:/data'
        image: 'portainer/portainer-ce:latest'
        networks:
            - net
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.portainer.loadbalancer.server.port=9000"
            # - "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
            - "traefik.http.routers.portainer.rule=Host(`portainer.docker`)"

volumes:
    portainer_data:

networks:
    net:
        external: true
